import type { Metadata } from "next";

import "./globals.css";
import { montserrat } from "./fonts";
import CookiesWrapper from "@/components/Wrapper/CookiesWrapper";

export const metadata: Metadata = {
  title: "Finnova",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable}`}>
      <body className={`antialiased font-Montserrat`}>
        <CookiesWrapper>{children}</CookiesWrapper>
      </body>
    </html>
  );
}
