import type { Metadata } from "next";

import "./globals.css";
import { montserrat } from "./fonts";

export const metadata: Metadata = {
  title: "Finnova",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable}`}>
      <body className={`antialiased font-Montserrat`}>{children}</body>
    </html>
  );
}
